name: "Setup"
description: "Checkout, install Nix, cache Nix store, and enter devShell"
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - name: Cache Nix store
      uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6.1.3
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        purge: true
        purge-prefixes: nix-${{ runner.os }}-

    - name: Set up devShell
      run: nix develop
      shell: bash
