name: Setup Nix
description: Install Nix, cache Nix store, and set up devShell
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@63ca48f939ee3b8d835f4126562537df0fee5b91 # v32
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - name: Cache Nix store
      uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6.1.3
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        purge: true
        purge-prefixes: nix-${{ runner.os }}-

    - name: Set up devShell
      run: nix develop
      shell: bash
